spring.cloud:
  function:
    definition: graalSupplier;graalUppercaseFunction;graalLoggingConsumer
  stream:
    bindings:
      graalSupplier-out-0:
        destination: graalUppercaseFunction-in-0
      graalLoggingConsumer-in-0:
        destination: graalUppercaseFunction-out-0
