#@data/values-schema
---
groups:
  - name: "group name"
    smoke_tests:
    - name: "smoke test name"
      app_test: true
      test: true
      slack:
        channel: ""
        on_success: false
        on_failure: false