anchors:
  git-repo-resource-source: &git-repo-resource-source
    uri: "https://github.com/((github-organization))/((github-repository)).git"
    username: ((github-username))
    password: ((github-password))
    branch: ((branch))
  registry-image-resource-source: &registry-image-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((milestone))
  gradle-enterprise-task-params: &gradle-enterprise-task-params
    GRADLE_ENTERPRISE_ACCESS_KEY: ((gradle_enterprise_secret_access_key))
    GRADLE_ENTERPRISE_CACHE_USERNAME: ((gradle_enterprise_cache_user.username))
    GRADLE_ENTERPRISE_CACHE_PASSWORD: ((gradle_enterprise_cache_user.password))
resources:
- name: git-repo
  type: git
  icon: github
  source:
    <<: *git-repo-resource-source
- name: ci-images-git-repo
  type: git
  icon: github
  source:
    uri: https://github.com/((github-organization))/((github-repository)).git
    branch: ((branch))
    paths: ["ci/images/*"]
- name: ci-image
  type: registry-image
  icon: docker
  source:
    <<: *registry-image-resource-source
    repository: ((docker-hub-organization))/((github-repository))-ci
jobs:
- name: build-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - get: git-repo
  - task: build-ci-image
    privileged: true
    file: git-repo/ci/tasks/build-ci-image.yml
    output_mapping:
      image: ci-image
    vars:
      ci-image-name: ci-image
  - put: ci-image
    params:
      image: ci-image/image.tar
- name: command-line-runner
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
  - do:
    - task: smoke-test
      image: ci-image
      privileged: true
      timeout: ((task-timeout))
      file: git-repo/ci/tasks/smoke-test.yml
      params:
        BRANCH: ((branch))
        SMOKE_TEST: command-line-runner
        <<: *gradle-enterprise-task-params
- name: webflux-netty
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
  - do:
    - task: smoke-test
      image: ci-image
      privileged: true
      timeout: ((task-timeout))
      file: git-repo/ci/tasks/smoke-test.yml
      params:
        BRANCH: ((branch))
        SMOKE_TEST: webflux-netty
        <<: *gradle-enterprise-task-params
- name: webmvc-tomcat
  serial: true
  public: true
  plan:
  - get: ci-image
  - get: git-repo
  - do:
    - task: smoke-test
      image: ci-image
      privileged: true
      timeout: ((task-timeout))
      file: git-repo/ci/tasks/smoke-test.yml
      params:
        BRANCH: ((branch))
        SMOKE_TEST: webmvc-tomcat
        <<: *gradle-enterprise-task-params
groups:
- name: "smoke-tests"
  jobs:
    - "command-line-runner"
    - "webflux-netty"
    - "webmvc-tomcat"
- name: "ci-images"
  jobs:
    - "build-ci-images"
