name: Boot Smoke Tests | Boot Tcf
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  boot_tcf_test:
    name: Boot Tcf Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:boot-tcf
      task: test
  boot_tcf_native_test:
    name: Boot Tcf Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:boot-tcf
      task: nativeTest
