name: Boot Smoke Tests | Freemarker Webflux
on:
  push:
    branches:
      - '3.1.x'
jobs:
  freemarker_webflux_app_test:
    name: Freemarker Webflux App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:freemarker-webflux
      task: appTest
  freemarker_webflux_native_app_test:
    name: Freemarker Webflux Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:freemarker-webflux
      task: nativeAppTest
