name: Boot Smoke Tests | Actuator Webmvc Mgmt Port
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  actuator_webmvc_mgmt_port_app_test:
    name: Actuator Webmvc Mgmt Port App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:actuator-webmvc-mgmt-port
      task: appTest
  actuator_webmvc_mgmt_port_native_app_test:
    name: Actuator Webmvc Mgmt Port Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:actuator-webmvc-mgmt-port
      task: nativeAppTest
