name: Boot Smoke Tests | Flyway
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  flyway_app_test:
    name: Flyway App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:flyway
      task: appTest
  flyway_native_app_test:
    name: Flyway Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:flyway
      task: nativeAppTest
