name: Boot Smoke Tests | Mustache Webflux
on:
  push:
    branches:
      - '3.1.x'
jobs:
  mustache_webflux_app_test:
    name: Mustache Webflux App Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: boot:mustache-webflux
      task: appTest
  mustache_webflux_native_app_test:
    name: Mustache Webflux Native App Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: boot:mustache-webflux
      task: nativeAppTest
