name: Framework Smoke Tests | Tcf
on:
  schedule:
    - cron : '0 0 * * *'
jobs:
  tcf_test:
    name: Tcf Test
    uses: ./.github/workflows/smoke-test-jvm.yml
    secrets: inherit
    with:
      project: framework:tcf
      task: test
  tcf_native_test:
    name: Tcf Native Test
    uses: ./.github/workflows/smoke-test-native.yml
    secrets: inherit
    with:
      project: framework:tcf
      task: nativeTest
